### ISSUE TITLE
How can I solve this problem？How to run the program？

### ISSUE THREAD

**Issue by outsider7777** [arturandre/tree-wires#1]
usage: It has a single parameter indicating the 'mode' of use:

train: Trains the default network as defined 'hardcodedly'
evaluate: Evaluates the default network
predict: Creates an output file with predictions for each image
classifier1.0.py: error: the following arguments are required: mode, checkpoint

**Comment by outsider7777** [comment]
![Uploading 1656916217553.jpg…]()

**Comment by outsider7777** [comment]
![1](https://user-images.githubusercontent.com/93963511/177095184-8ef3c15b-a357-4afe-822d-82678c30c025.jpg)

**Comment by arturandre** [comment]
Hi, have you executed the `test_model.py` script, or have you tried to run directly the `classifier1.0.py`?
The former encapsulates the parameters (e.g. `mode`, `save_checkpoint`, etc.) required by the latter.

**Comment by outsider7777** [comment]
executed the test_model.py script but Is still an error.

**Comment by outsider7777** [comment]
![1](https://user-images.githubusercontent.com/93963511/177258634-877e891f-cc20-42c8-b4f5-33b9680d1745.jpg)

**Comment by outsider7777** [comment]
Are there some files missing ?

**Comment by arturandre** [comment]
> Are there some files missing?

There were some incorrect references to paths/files. Please let me know if the new commands (written on the repository page) work for testing the (pre-)trained models and training new ones.

**Comment by arturandre** [comment]
I'll close this issue due to inactivity, but if the issue persists please don't hesitate to re-open it.
